package Interfaces;

import gestionClassement.ClassementAnnuel;
import gestionPlannification.*;
import model.*;

/**
 *
 * @author Arya
 */
public class InterfaceRally extends javax.swing.JFrame {
    private InterfaceConsultation interconsul;
    private Donnee d;

    @Override
    public void setDefaultCloseOperation(int operation) {
        this.setVisible(false);
        
    }

    /**
     * Creates new form InterfaceRally
     */
    public InterfaceRally(Donnee d, InterfaceConsultation interconsul) {
        initComponents();
        this.d = d;
        this.interconsul=interconsul;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        zone_dateLimite = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        zone_numEdi = new javax.swing.JTextField();
        label_annee = new javax.swing.JLabel();
        label_titre1 = new javax.swing.JLabel();
        zone_anneeEd = new javax.swing.JTextField();
        label_dateDebE = new javax.swing.JLabel();
        label_DateFinE = new javax.swing.JLabel();
        zone_dateDeb = new javax.swing.JTextField();
        zone_dateFin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        zone_pays = new javax.swing.JTextField();
        label_titre = new javax.swing.JLabel();
        label_nomR = new javax.swing.JLabel();
        label_surface = new javax.swing.JLabel();
        label_ville = new javax.swing.JLabel();
        label_pays = new javax.swing.JLabel();
        checkBox_SuperR = new javax.swing.JCheckBox();
        zone_surf = new javax.swing.JComboBox<>();
        button_creaR = new javax.swing.JButton();
        zone_nomR = new javax.swing.JTextField();
        zone_ville = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame2.setVisible(true);

        jButton1.setText("Valider");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero d'édition :");

        label_annee.setText("Année :");

        label_titre1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_titre1.setText("Création d'une édition");

        label_dateDebE.setText("Date début édition :");

        label_DateFinE.setText("Date fin édition :");

        jLabel1.setText("Date limite inscription :");

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(label_titre1))
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame2Layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(zone_dateLimite))
                        .addGroup(jInternalFrame2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(label_DateFinE)
                            .addGap(18, 18, 18)
                            .addComponent(zone_dateFin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame2Layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(label_dateDebE)
                                .addComponent(label_annee))
                            .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(zone_dateDeb, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(zone_numEdi, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                        .addComponent(zone_anneeEd)))))))
                .addGap(0, 181, Short.MAX_VALUE))
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(label_titre1)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zone_numEdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(label_annee)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(zone_anneeEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_dateDebE)
                    .addComponent(zone_dateDeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_DateFinE)
                    .addComponent(zone_dateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(zone_dateLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(91, 91, 91))
        );

        jTabbedPane1.addTab("Edition", jInternalFrame2);

        jInternalFrame1.setVisible(true);

        label_titre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_titre.setText("Création d'un rallye");

        label_nomR.setText("Nom :");

        label_surface.setText("Type surface :");

        label_ville.setText("Ville :");

        label_pays.setText("Pays :");

        checkBox_SuperR.setText("Super Rallye");
        checkBox_SuperR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        checkBox_SuperR.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        zone_surf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "asphalte", "terre" }));

        button_creaR.setText("Valider");
        button_creaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_creaRActionPerformed(evt);
            }
        });

        zone_nomR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zone_nomRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(label_pays)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(zone_pays))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(label_ville)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(zone_ville, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(label_surface)
                        .addGap(18, 18, 18)
                        .addComponent(zone_surf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(label_nomR)
                        .addGap(90, 90, 90)
                        .addComponent(zone_nomR, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkBox_SuperR))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(label_titre)
                .addGap(82, 210, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_creaR)
                .addGap(230, 230, 230))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_titre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(zone_nomR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(label_nomR)))
                .addGap(23, 23, 23)
                .addComponent(checkBox_SuperR)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_surface)
                    .addComponent(zone_surf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_ville)
                    .addComponent(zone_ville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_pays)
                    .addComponent(zone_pays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(button_creaR)
                .addGap(55, 55, 55))
        );

        jTabbedPane1.addTab("Rallye", jInternalFrame1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_creaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_creaRActionPerformed
        //Qd on valide la création d'un rallye

        String nomR = this.zone_nomR.getText();
        String villeR = this.zone_ville.getText();
        String paysR = this.zone_pays.getText();
        String surface = this.zone_surf.getSelectedItem().toString();
        //String date_deb = this.zone_dateDeb.getText();
        //String date_fin = this.zone_dateFin.getText();
        boolean etreSuper = false;
        if (this.checkBox_SuperR.isSelected()) {
            etreSuper = true;
        }
        Ville v = new Ville(villeR, paysR);
        Rallye r = new Rallye(nomR, etreSuper, surface, v);

        System.out.println(nomR);
        d.ajoutRallye(r);
         this.interconsul.setlstRallye(d.getLstRallye());
        for (Rallye rs : d.getLstRallye()) {
            System.out.println(rs.getNomR());
        }
    }//GEN-LAST:event_button_creaRActionPerformed

    private void zone_nomRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zone_nomRActionPerformed

    }//GEN-LAST:event_zone_nomRActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int numEdi = Integer.valueOf(this.zone_numEdi.getText());
        int anneeEdi = Integer.valueOf(this.zone_anneeEd.getText());
        String date_deb = this.zone_dateDeb.getText();
        String date_fin = this.zone_dateFin.getText();
        String date_limite = this.zone_dateLimite.getText();

        ClassementAnnuel ca = new ClassementAnnuel(anneeEdi);
        Edition ed = new Edition(numEdi, ca, date_deb, date_fin, date_limite);

        d.ajoutEdition(ed);

//        System.out.println(numEdi);        
//        for(Edition edi : d.getLstEdition()){
//            System.out.println(edi.getNumEdition());
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_creaR;
    private javax.swing.JCheckBox checkBox_SuperR;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_DateFinE;
    private javax.swing.JLabel label_annee;
    private javax.swing.JLabel label_dateDebE;
    private javax.swing.JLabel label_nomR;
    private javax.swing.JLabel label_pays;
    private javax.swing.JLabel label_surface;
    private javax.swing.JLabel label_titre;
    private javax.swing.JLabel label_titre1;
    private javax.swing.JLabel label_ville;
    private javax.swing.JTextField zone_anneeEd;
    private javax.swing.JTextField zone_dateDeb;
    private javax.swing.JTextField zone_dateFin;
    private javax.swing.JTextField zone_dateLimite;
    private javax.swing.JTextField zone_nomR;
    private javax.swing.JTextField zone_numEdi;
    private javax.swing.JTextField zone_pays;
    private javax.swing.JComboBox<String> zone_surf;
    private javax.swing.JTextField zone_ville;
    // End of variables declaration//GEN-END:variables
}
